server:
  port: 55726
logging:
  level:
    org:
      springframework:
        security: INFO
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.98.100.242:3306/rkw_test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: rkwtest
    password: tEst@2013